### ISSUE TITLE
Interface for Vagrant and/or Ansible

### ISSUE THREAD

**Issue by joaocc** [mindreframer/hetzner-stuff#1]
Hi,
Have you thought of creating an interface for Hetzner on Vagrant and/or Ansible?
Thanks

**Comment by mindreframer** [comment]
No, I have not. :) It might be interesting, but I'm currently not using hetzner due to their inaceptable DDOS policy. Can I close the issue?

**Comment by joaocc** [comment]
Sure. Btw, what is the issue with their DDOS policy? Thx

**Comment by mindreframer** [comment]
Heztner will null-route all your traffic. 

http://www.spigotmc.org/threads/over-2-gpbs-ddos-what-should-i-do.138/

They just don't provide a service to deal with malicious traffic attacks and you are basically exposed to any script-kiddie to damage your business and extort money from you. Also the support in hetzner is sub-optimal. But it is good hardware to run utilities servers and test/stagings environments.

**Comment by joaocc** [comment]
thx!
